spring:
    application:
        name: CHUNJAE-Full5-Final

    datasource:
        url: jdbc:mariadb://localhost:3306/db1
        username: root
        password: mariadb
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                show_sql: true
        hibernate:
            ddl-auto: validate

    thymeleaf:
        cache: false

    data:
        web:
            pageable:
                one-indexed-parameters: true

server:
    port: 8080
    servlet:
        encoding:
            charset: utf-8
            enabled: true
            force: true

logging:
    level:
        sql: debug
        org.hibernate.type: trace
        com.chunjae.chunjaefull5final: info